services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file: ".env"
    depends_on:
      - postgresql
    container_name: "Backend"


  postgresql:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: "Postgres"
    env_file: ".env"


volumes:
  postgres_data: